### ISSUE TITLE
can barplot3d function draw dashed line ？

### ISSUE THREAD

**Issue by cby01** [cpwardell/barplot3d#3]
I want draw grid lines use dashed line，but I don't know how to modify it , can you help me?
in line 96 of barplot3d.R, I add lty=2, it seems changed nothing. 
rgl::grid3d("z-+",col="gray",lty=2)

**Comment by cpwardell** [comment]
I'm afraid that the rgl package doesn't support dashed or dotted lines, so it's not possible to do this.  I am as disappointed as you are, it would be really cool.

**Comment by cby01** [comment]
Thank you for help me！ the rgl package seems nolonger update, so it's not possible to change. Very disappointed!
